language: python
dist: xenial  # https://github.com/travis-ci/travis-ci/issues/9831

os:
  - linux

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy2.7-6.0
  - pypy3.5-6.0

before_install:
  - sudo chmod 0777 /var/run

# https://github.com/WeblateOrg/translation-finder/blob/master/.travis.yml#L20-L26
matrix:
  include:
  - os: windows
    python: 3.7
    before_install:
      - choco install python3
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      - python -m pip install --upgrade pip wheel

install:
  - pip install "coverage>=3.6" "nose>=1.3.0" "flake8>=2.1" "coveralls>=0.3" "mock>=2.0.0" "psutil>=5.4.8"
  - pip install -e .

script:
  - echo $TRAVIS_PYTHON_VERSION
  - flake8 -v --show-source --ignore=E501,W391 .
  - nosetests -v --with-coverage --cover-package=pid

after_success:
  - coveralls
