language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy2.7-6.0
  - pypy3.5-6.0

before_install:
  - sudo chmod 0777 /var/run

install:
  - pip install flake8 pytest pytest-cov
  - dpkg --compare-versions $TRAVIS_PYTHON_VERSION ge 3.3 || pip install "mock>=2.0.0"
  - pip install -e .

script:
  - echo $TRAVIS_PYTHON_VERSION
  - flake8 --show-source --ignore=E501,W391 .
  - PYTHONPATH=. pytest -v -x --cov=pid

after_success:
  - coveralls
