language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
  - pypy3

before_install:
  - sudo chmod 0777 /var/run

install:
  - pip install "coverage>=3.6" "nose>=1.3.0" "flake8>=2.1" "coveralls>=0.3" "mock>=2.0.0" "psutil>=5.4.8"
  - pip install -e .

script:
  - echo $TRAVIS_PYTHON_VERSION
  - flake8 -v --show-source --ignore=E501,W391 .
  - nosetests -v --with-coverage --cover-package=pid

after_success:
  - coveralls
