language: python

# Explicitly specifying default OS for clarity
os: linux

matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  # Xenial is required for PyPy and 3.7 builds
  # https://github.com/travis-ci/travis-ci/issues/9831
  - python: pypy2.7-6.0
    dist: xenial
  - python: pypy3.5-6.0
    dist: xenial
  - python: 3.7
    dist: xenial

  # Python is not natively supported in windows yet, have to install it through shell script
  # https://github.com/WeblateOrg/translation-finder/blob/master/.travis.yml#L20-L33
  - os: windows
    language: sh
    python: 2.7
    env:
      - PY_VERSION_BASE=2 PY_VERSION=2.7.15 PY_VERSION_PATH=27
  - os: windows
    language: sh
    python: 3.5
    env:
      - PY_VERSION_BASE=3 PY_VERSION=3.5.4 PY_VERSION_PATH=35
  - os: windows
    language: sh
    python: 3.6
    env:
      - PY_VERSION_BASE=3 PY_VERSION=3.6.8 PY_VERSION_PATH=36
  - os: windows
    language: sh
    python: 3.7
    env:
      - PY_VERSION_BASE=3 PY_VERSION=3.7.2 PY_VERSION_PATH=37

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo chmod 0777 /var/run;
    fi

install:
  # Install python on windows machine, environment variables should be set in the matrix above
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      echo "/c/Python${PY_VERSION_PATH}:/c/Python${PY_VERSION_PATH}/Scripts:$PATH";
      choco install python${PY_VERSION_BASE} --version ${PY_VERSION};
      export PATH="/c/Python${PY_VERSION_PATH}:/c/Python${PY_VERSION_PATH}/Scripts:$PATH";
      python -m pip install --upgrade pip wheel;
    fi
  - pip install "coverage>=3.6" "nose>=1.3.0" "flake8>=2.1" "coveralls>=0.3" "mock>=2.0.0" "psutil>=5.4.8"
  - pip install -e .

script:
  - echo $TRAVIS_PYTHON_VERSION
  - flake8 -v --show-source --ignore=E501,W391 .
  - nosetests -v --with-coverage --cover-package=pid

after_success:
  - coveralls
