language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
  - pypy3

before_install:
  - sudo chmod 0777 /var/run

install:
  - pip install "coverage>=3.6" "nose>=1.3.0" "flake8>=2.1" "coveralls>=0.3"
  - pip install -e .

script:
  - flake8 --show-source --ignore=E501,W391 .
  - nosetests -v --with-coverage --cover-package=pid

after_success:
  - coveralls
